### ISSUE TITLE
"npm run" fails 

### ISSUE THREAD

**Issue by nettsite** [devaslanphp/project-management#84]
Hi,

If I do `npm run build` or `npm run dev` I get the following error:

```
:~/NettSite/helper$ npm run build

> build
> vite build

file:///home/william/NettSite/helper/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```
Laravel 9.45.1
node v12.22.9
npm 8.5.1
Ubuntu 22.04

package.json:
```
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.5.3",
        "@tailwindcss/typography": "^0.5.7",
        "autoprefixer": "^10.4.13",
        "axios": "^1.1.2",
        "laravel-vite-plugin": "^0.6.1",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "sass": "^1.55.0",
        "tailwindcss": "^3.2.1",
        "tippy.js": "^6.3.7",
        "vite": "^3.2.6"
    },
    "dependencies": {
        "flowbite": "^1.5.3"
    }
}
```

**Comment by mihaisolomon** [comment]
Hey,

Try to update node and npm to newer versions. I personally use 

```
Node: v:16.19
Npm: v8.19
````
